### ISSUE TITLE
There isn't an onyxia-api hosted at /api

### ISSUE THREAD

**Issue by demangejeremy** [InseeFrLab/devoxx-2023#1]
Malgré une exécution étape par étape, j'ai ce problème au moment de la mise en place de l'authentification, ça se produit juste après avoir été loggé sur Keycloak :

```
There isn't an onyxia-api hosted at /api Check the ONYXIA_API_URL environnement variable you provided with docker run.
```

/api/public/configuration est en erreur 401, problème d'autorisation...

En suivant les indications de https://docs.onyxia.sh/ ; j'ai aussi le même problème.

Est-ce que quelque chose à changer entre temps, dans les environnements du front ou de l'API ?
J'essaye de creuser de mon côté pour voir ce qu'il ne va pas.

Merci par avance pour votre aide :)

**Comment by olevitt** [comment]
Hello,  
L'erreur UI est une erreur générique.  
Mais le 401 sur `/api/public/configuration` n'est pas normal. Tu peux regarder les logs du pod API pour en savoir plus mais en général d'expérience ça ressemble à l'API qui arrive pas à contacter le keycloak pour choper la clé publique pour la validation des tokens. Vérifie que le pod de l'API peut joindre niveau réseau le keycloak et aussi que le certificat du keycloak est bien valide / reconnu par le pod de l'API. Si tu utilises un certificat interne / autosigné tu as une property que tu peux activer pour désactiver la vérif du certif keycloak par l'API.
Édit : `keycloak.disable-trust-manager`, cf https://github.com/inseefrlab/onyxia-api#configuration
Hésite pas aussi à rejoindre le slack du projet : https://join.slack.com/t/3innovation/shared_invite/zt-19tht9hvr-bZGMdW8AV_wvd5kz3wRSMw 
Ça peut faciliter le débug

**Comment by demangejeremy** [comment]
Merci @olevitt pour cette réactivité :)

Corrigé avec : 
`keycloak.ssl-required: none`
(bien évidemment, ça va de soit que ce n'est pas une bonne chose à mettre en prod)

Certificat valide avec Let's Encrypt, tous les pods sont joignables entre-eux... Sans doute quelque chose que j'ai dû louper dans ma config.
